### ISSUE TITLE
Create internal links between features

### ISSUE THREAD

**Issue by sshushliapin** [picklesdoc/pickles#189] opened 2015-02-10 17:41 UTC
I want to create internal links between my features, so that I can easily navigate between them.

It can be pretty useful if I want to build a glossary and access it's items from other specs. This feature is implemented in [GitHub Wiki](https://help.github.com/articles/adding-links-to-wikis/#using-a-wiki-markup-syntax-to-make-links) pages, would be nice to see it in pickles:

> Using a wiki markup syntax to make links
> 
> You can also create links with the wiki format of **[[Link Text|WikiLink]]**. In this case, WikiLink is the name of your wiki page, not the full URL. Please note that support for WikiLinks in Asciidoc has been removed.

**Comment by dirkrombauts** [comment] 2015-02-11 10:27
This is an interesting idea ... I suppose the WikiLink part would refer to the name of a Feature, right? Or do you what do you want to link to?

**Comment by sergeyshushlyapin** [comment] 2015-02-11 12:38
So, there are two options here. As far as I see, at the moment the same feature name is used as a menu title as well as a page URL. In this case I would use the simplified internal link definition:

    [[My Feature Name]]

The second option might be considered as an independent wish. I would like the `Feature Name Look Like a Page Title in My Menu` and `feature-url-to-be-represented-in-lower-case-in-address-bar`. In this case the internal link for feature "Create a user account" would look like the following:

    [[Create a user account|create-a-user-account]]

**Comment by dirkrombauts** [comment] 2015-02-11 17:54
I like it! Do you have any .NET development experience yourself? I would be happy to accept push requests for this one ;-)

**Comment by sergeyshushlyapin** [comment] 2015-02-12 14:46
Ok, I'll try to look on it in a meantime :)  
I've done some [raw prototyping](https://github.com/sergeyshushlyapin/pickles/commit/ff0e9f781ba76bdea9a4152c5700f073615fd7eb) but it *works* only in tests so far. I suppose I miss smth in DI configuration.

**Comment by dirkrombauts** [comment] 2015-02-12 14:52
You're probably right that it's a problem with the DI config - but I don't see it immediately myself :-(

**Comment by sergeyshushlyapin** [comment] 2015-03-05 16:24
It's possible to build links between features using relative paths:

`[Introduction](/index.html#Introduction.feature)`

Clicking the link sets the correct `Introduction.feature` URL in the address bar, but unfortunately the page isn't opened.. I suppose the problem is in missing bindings that are applied to the menu items.. 

Is there any quick solution for this? Thanks!

**Comment by dirkrombauts** [comment] 2015-03-05 20:45
I suppose you are talking about the DHTML version, right?

I don't feel confident saying anything about the DHTML version since I haven't contributed anything to it :-(

Feel free to have a go at it yourself, though ...

**Comment by dirkrombauts** [comment] 2020-07-14 13:15
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.

**Closed by dirkrombauts** 2020-07-14 13:15 UTC
Labels: newfeature
