### ISSUE TITLE
[bug] Paths are changed to backslashes even when not necessary

### ISSUE THREAD

**Issue by AntoineTheb** [picklesdoc/pickles#468] opened 2017-06-26 16:14 UTC
```
OS: Arch Linux
Product: Pickles.CommandLine 2.16.0
Mono version: 5.0.0
Formatter: DHTML
``` 
I'm currently trying to use Pickles on Linux, but I'm encountering a problem with paths. When I generate documentation in the DHTML format, everything looks fine at first glance, but I when I try to select a feature file, nothing happens.

![peek 2017-06-26 12-06](https://user-images.githubusercontent.com/10272382/27548781-f11201dc-5a67-11e7-8dc4-6bf3cabbc3b8.gif)

Following the errors in the console, I eventually arrive at this method:
![deepinscreenshot20170626120811](https://user-images.githubusercontent.com/10272382/27548831-2592b35c-5a68-11e7-95da-67d832f8bf8f.png)

And by putting a breakpoint there, we can see the cause of the problems
![deepinscreenshot20170626121017](https://user-images.githubusercontent.com/10272382/27548933-7e552eca-5a68-11e7-975a-9c570302c9ad.png)

The feature files tree that is loaded has forward slashes (which makes sense on my setup), but line 90 of `featureSearch.js` tries to search with backslashes no matter. Manually editing the file and removing this line solves the issue. I do not know if removing this line breaks things on Windows or Mac.

Anyone else having this issue ?
Thank you.

**Comment by dirkrombauts** [comment] 2017-06-27 08:26
So if I understand correctly, the problem is that the search routine uses backslashes at all times. Right?

You could send me a pull request with your change and I will try it on Windows.

**Comment by AntoineTheb** [comment] 2017-06-27 18:20
Thank you ! It seems like it, yes. The jsonp tree of feature files (in `pickledFeatures.js`) has forward slashes (on my architecture) and the javascript method that finds features in this tree uses backslashes no matter how the tree is built.

**Comment by dirkrombauts** [comment] 2020-07-14 13:13
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.

**Closed by dirkrombauts** 2020-07-14 13:13 UTC
Labels: released-as-experimental
