### ISSUE TITLE
Scenario Outline Example test results icon's in html but not dhtml

### ISSUE THREAD

**Issue by Tempuskg** [picklesdoc/pickles#496] opened 2017-10-28 23:03 UTC
I like how the test result icon's show at the Feature, Scenario and Scenario Outline Example levels in the html documentation format. In the dhtml documentation format the test result icon's only show at the Feature and Scenario levels. Is anyone working on getting the test result icon's showing at the Scenario Outline Example level for the dhtml documentation format?

**Comment by dirkrombauts** [comment] 2017-10-30 09:03
Hi,

As far as I know, no-one is working on that. Feel free to have a go at it :-)  The DHTML version uses the JSON output format as its data source, so it may be that you have to change that one first. It's important that any changes you make are not breaking.

**Comment by DominikBaran** [comment] 2018-01-09 19:46
hi. Just for your information. I have added that change to the Pickles code (hope did not break anything else). You could find the code in my PR:
https://github.com/picklesdoc/pickles/pull/501

**Comment by dirkrombauts** [comment] 2018-01-26 19:08
@Tempuskg @DominikBaran could you take the latest development build and verify that the problem is now solved?

**Comment by DominikBaran** [comment] 2018-01-28 19:52
@dirkrombauts : After rebuild the project with all new changes from develop branch - it looks good for me.

**Comment by dirkrombauts** [comment] 2018-01-30 12:06
@DominikBaran I'll try to do it on thursday evening (central european time). I'm fully booked until then.

**Comment by dirkrombauts** [comment] 2018-02-02 14:43
Resolved in #502

**Closed by dirkrombauts** 2018-02-02 14:43 UTC
